server:
<<<<<<< HEAD
  port: 8080
JWT_SECRET_KEY: univalleclavesecreta123456789012345678901234567890123456789
=======
  port: 8081
jwt:
  secret: univalleClaveSecreta
>>>>>>> d8208340c1d1ab84d0c923e1f1115bbbba4a14a4
  
  
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: Auth
              uri: lb://AUTH 
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=1
            - id: Subasta
              uri: lb://Subasta
              predicates:
                - Path=/api/subasta/**
            - id: oferta-service
              uri: lb://oferta
              predicates:
                - Path=/api/ofertas/**
            - id: pedido-service
              uri: lb://PedidoRastreo
              predicates:
                - Path=/api/pedidos/**
            - id: chat-service
              uri: lb://Microservicio-Chat
              predicates:
                - Path=/api/chat/**
            - id: monitoreo-service
              uri: lb://MONITOREO
              predicates:
                - Path=/api/monitoreo/**
            - id: metrics-service
              uri: lb://MONITOREO
              predicates:
                - Path=/api/metrics/**
              filters:
                - StripPrefix=1
            - id: test-service
              uri: lb://MONITOREO
              predicates:
                - Path=/api/test/**
              filters:
                - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
