server:
  port: 8081
jwt:
  secret: univalleClaveSecreta
  
  
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: Auth
          uri: lb://AUTH
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: Subasta
          uri: lb://SUBASTA
          predicates:
            - Path=/api/subasta/**
          filters:
            - StripPrefix=1
        - id: oferta-service
          uri: lb://OFERTA
          predicates:
            - Path=/api/ofertas/**
          filters:
            - StripPrefix=1
        - id: pedido-service
          uri: lb://PEDIDORASTREO
          predicates:
            - Path=/api/pedidos/**
          filters:
            - StripPrefix=1
        - id: chat-service
          uri: lb://MICROSERVICIO-CHAT
          predicates:
            - Path=/api/chat/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
