name: Java CI con Maven y cobertura JaCoCo

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache de dependencias Maven
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Compilar y testear con Maven (con cobertura)
      run: mvn clean verify

    - name: Subir reporte de cobertura JaCoCo
      uses: actions/upload-artifact@v3
      with:
        name: jacoco-report
        path: target/site/jacoco/ 